# Generated by Django 4.0.3 on 2022-03-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='type',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
